version: '2.4'

services:
  backend:
    restart: always
    hostname: backend
    depends_on:
      - postgres
    networks:
      - demo_server_net
    ports:
      - "4242:4242"
    build:
      context: ./backend
    volumes:
      - ./backend/:/backend:delegated

  frontend:
    depends_on:
      - backend
    restart: always
    hostname: frontend
    networks:
      - demo_server_net
    build:
      context: ./frontend
      target: prod
    ports:
      - "4343:4343"
    volumes:
      - ./frontend/src/:/frontend/src/:delegated

  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./postgres_vol/:/var/lib/postgresql/data:delegated
    networks:
      - demo_server_net
    environment:
      POSTGRES_PASSWORD:    ${POSTGRES_PASSWORD}
      POSTGRES_USER:        ${POSTGRES_USER}
      POSTGRES_DB:          ${POSTGRES_DB}


networks:
  demo_server_net:
    driver: bridge
    name: demo_server_net
