version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      NODE_VERSION: 18.15.0

    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - restore_cache:
          keys:
            - v1-python-dependencies-{{ checksum "./backend/requirements.txt" }}
            - v1-python-dependencies-
      - run:
          name: Install Python dependencies
          command: pip install -r ./backend/requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-python-dependencies-{{ checksum "./backend/requirements.txt" }}

      # Install Vue.js dependencies
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "./frontend/package.json" }}
            - v1-node-dependencies-
      - run:
          name: Install Vue.js dependencies
          command: yarn --cwd ./frontend install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum ./frontend/"package.json" }}

      # Build Vue.js application
      - run:
          name: Build Vue.js App
          command: yarn --cwd ./frontend build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
