version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      NODE_VERSION: 18.15.0
    steps:
      - checkout
      - run:
          name: Update OS
          command: sudo apt update #&& sudo apt upgrade -y
      - run:
          name: Update pip
          command: python3.8 -m pip install --upgrade pip
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Swap node versions
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --install' >> $BASH_ENV
            source $BASH_ENV
            nvm install --lts
            nvm use 18.15.0
      - restore_cache:
          keys:
            - v1-python-dependencies-{{ checksum "./backend/requirements.txt" }}
            - v1-python-dependencies-
      - run:
          name: Install Python dependencies
          command: pwd && pip3 install -r ./backend/requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip3
          key: v1-python-dependencies-{{ checksum "./backend/requirements.txt" }}
#      - restore_cache:
#          keys:
#            - v1-node-dependencies-{{ checksum "./frontend/package.json" }}
#            - v1-node-dependencies-
      - run:
          name: Install Vue.js dependencies
          command: |
            nvm use 18.15.0
            yarn --cwd ./frontend install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum "./frontend/package.json" }}
      - run:
          name: Build Vue.js App
          command: |
            nvm use 18.15.0
            yarn --cwd ./frontend build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
