version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      NODE_VERSION: 18.15.0
    steps:
      - checkout
      - run:
          name: Update OS
          command: sudo apt update
      - restore_cache:
          keys:
            - docker-binary-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Docker
          command: |
            if [ ! -f /usr/local/bin/docker ]; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker ${USER}
            fi
      - save_cache:
          key: docker-binary-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/bin/docker
      - restore_cache:
          keys:
            - docker-compose-binary-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Docker Compose
          command: |
            if [ ! -f /usr/local/bin/docker-compose ]; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
      - run:
          name: Run demo server
          command: sudo docker compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
