version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      NODE_VERSION: 18.15.0
    steps:
      - checkout
      - run:
          name: Update OS
          command: sudo apt update #&& sudo apt upgrade -y
      - run:
          name: Update pip
          command: python3.8 -m pip install --upgrade pip
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install --lts
            nvm alias default v18.15.0
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
#      - restore_cache:
#          keys:
#            - v1-node-dependencies-{{ checksum "./frontend/package.json" }}
#            - v1-node-dependencies-
      - run:
          name: Install Python dependencies
          command: pip3 install -r ./backend/requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip3
          key: v1-python-dependencies-{{ checksum "./backend/requirements.txt" }}
      - run:
          name: Install Vue.js dependencies
          command: yarn --cwd ./frontend install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum ./frontend/"package.json" }}

      # Build Vue.js application
      - run:
          name: Build Vue.js App
          command: yarn --cwd ./frontend build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
